apiVersion: certmanager.k8s.io/v1alpha1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod-cluster
  namespace: cert-manager
spec:
  acme:
    email: cc-wombat@alfirth.com
    http01: {}
    privateKeySecretRef:
      key: ""
      name: letsencrypt-prod-cluster
    server: https://acme-v02.api.letsencrypt.org/directory
